//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTMuonSach
    {
        public string MaMuon { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<decimal> GiaSach { get; set; }
    
        public virtual MuonSach MuonSach { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
