//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTraSach
    {
        public string MaTra { get; set; }
        public string MaSach { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> TienThue { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TraSach TraSach { get; set; }
    }
}
