//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public string MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SoThe { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
