//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhapSach()
        {
            this.CTNhapSaches = new HashSet<CTNhapSach>();
        }
    
        public string MaNhap { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapSach> CTNhapSaches { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
