//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.CTMuonSaches = new HashSet<CTMuonSach>();
            this.CTNhapSaches = new HashSet<CTNhapSach>();
            this.CTTraSaches = new HashSet<CTTraSach>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaDauSach { get; set; }
        public string TenTacGia { get; set; }
        public string TenNhaXuatBan { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTMuonSach> CTMuonSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapSach> CTNhapSaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTraSach> CTTraSaches { get; set; }
        public virtual DauSach DauSach { get; set; }
    }
}
